### ISSUE TITLE
Reorganize Output

### ISSUE THREAD

**Issue by mthbrown** [cado-security/varc#10]
Hi,

While initially looking at the output of **varc** on a Linux capture, I was a bit confused about what the contents of `/etc`, `/var` and similar  directories were until I realized that these just contain copies of the open files. Would it be better to have all of this under a directory such as `open_files`? I think it would make it clearer for anyone looking at the output. It would also mean that if you add additional functionality and capture additional files, they wouldn't be stored next to the opened file copies and can be stored in their own directories. Thanks

**Comment by chrisdoman** [comment]
@mthbrown Good idea. I've created https://github.com/cado-security/varc/pull/13 to do this.

**Comment by chrisdoman** [comment]
@mthbrown this has been added now with https://github.com/cado-security/varc/pull/13

I'll update the pip and binaries on the releases tab shortly.

Thank-you!
