### ISSUE TITLE
PyInstaller requirements

### ISSUE THREAD

**Issue by BlueSideStrongSide** [cado-security/varc#2]
python3 -m pip install -r ../requirements.txt
python3 -m PyInstaller --onefile ../varc.py

PyInstaller <-- not listed in the project as a requirements.txt. 

Pretty easy to install but would help and catch the error or provide a note in the batch to have users install the needed dependency. 

Error:
C:\Tools\varc\release>python -m PyInstaller --onefile ../varc.py
C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe: No module named PyInstaller

**Comment by chrisdoman** [comment]
Thank-you @BlueSideStrongSide ! I will make a PR adding the requirement shortly.

**Comment by chrisdoman** [comment]
Fixed with https://github.com/cado-security/varc/pull/5
